config/routes.rb
Rails.application.routes.draw do

  resources :documents

  get 'welcome/index'

  get 'password_resets/new'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :welcome do
    get 'welcome/index' => :new
    post 'welcome/index' => :create
    delete 'welcome/index' => :destroy
    delete 'welcome/logout' => :destroy
  end
  
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :welcome

  resources :users

  resources :rols

  resources :password_resets

  controller :users do
    get 'recover_password' => :recover_password
    post 'recover_password' => :recover_password 
    get 'new_recover_password' => :new_recover_password
    post 'new_recover_password' => :new_recover_password 
    get 'cambiar_password' => :cambiar_password
    post 'cambiar_password' => :cambiar_password
    get 'new_cambiar_password' => :new_cambiar_password
    post 'new_cambiar_password' => :new_cambiar_password
  end 

  

  root 'welcome#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
    @document = Document.new
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)


    carpeta = "Documents"
    @doc = params[:document][:link]
    unless @doc.nil?
      @docs = DataFile.save(@doc, carpeta)
    else
      redirect_to @document, notice: 'el Documento estaba en blanco.' 
    end
    @document.link = @docs
    @document.owner = session[:uname]
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    carpeta = "Documents"
      

    @doc = params[:document][:link]
    unless @doc.nil?
      @docs = DataFile.save(@doc, carpeta)
    else
      redirect_to @document, notice: 'el Documento estaba en blanco.' 
    end
    # @document.owner = session[:uname]
    # @document.link = @docs
    params[:document][:owner]=@docs
    params[:document][:link]=@docs
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :link, :owner)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document , :html => { :multipart => true } ) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.file_field :link %>
  </div>
  <div class="field">
    <%#= f.label :owner %><br>
    <%#= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Centro de Diabetes Monterrey</title>
<link rel="stylesheet" href="../css/960_24_col.css" type="text/css" />
<link rel="stylesheet" href="../css/main.css" type="text/css" />

<!-- Example assets -->
<link rel="stylesheet" type="text/css" href="../css/jcarousel.basic.css">
<script type="text/javascript" src="../jquery/jquery.js"></script>
<script type="text/javascript" src="../jquery/jquery.jcarousel.min.js"></script>
<script type="text/javascript" src="../jquery/jcarousel.basic.js"></script>

<!--[if IE]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<!--[if lte IE 7]>
  <script src="js/IE8.js" type="text/javascript"></script><![endif]-->
<!--[if lt IE 7]>
  <link rel="stylesheet" type="text/css" media="all" href="../css/ie6.css"/><![endif]-->

</head>
<body id="index" class="home">
<div id="google_custom_search"><!--Google Custom Search Code -->
  <script>
  (function() {
    var cx = '001121310335943621884:7wshjb_lvfu';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
</div>
  <div class="container_24"> <!---Inicio del grid -->
    <!--Botones para redes sociales -->
    <div id="siguenos" class="grid_5 push_16 siguenos">Siguenos en:
      <a href="http://www.facebook.com"><img src="../img/socialbutton_01.png"></a>
      <a href="http://www.twitter.com"><img src="../img/socialbutton_02.png"></a>
      <a href="http://www.youtube.com.mx"><img src="../img/socialbutton_03.png"></a>
    </div>
    <!-- Terminan botones para redes sociales -->
  <div class="clear">&nbsp;</div>
    <!--formulario de busqueda -->
    <div id="logo" class="grid_3"><a href="/index.html">
      <img src="../img/Logo.png" width="115" height="115"></a></div>
    <div id="Titulo" class="grid_12 titulo">Centro de Diabetes Monterrey</div>
    <div id="buscar" class="grid_5">
      <gcse:search></gcse:search>
      <!--   
      <INPUT TYPE="text" VALUE="Buscar..." size> 
        <INPUT TYPE="submit" VALUE="">-->
    </div>
    <!-- termina formulario de busqueda -->
  <div class="clear">&nbsp;</div> 
    <!-- Barra de herramientas -->
    <div id="btn_accesorios" class="grid_4">
      <a class="menuItem" href="/accesorios.html"><div class="menu1">Accesorios</div></a>
    </div>
    <div id="btn_cursos" class="grid_4">
      <a class="menuItem" href="/cursos.html"><div class="menu2">Cursos</div></a>
    </div>
    <div id="btn_nutricion" class="grid_4">
      <a class="menuItem" href="/nutricion.html"><div class="menu3">Nutrición</div></a>
    </div>
    <div id="btn_servicios" class="grid_4">
      <a class="menuItem" href="/servicios.html"><div class="menu4">Servicios</div></a>
    </div>
    <div id="btn_conocenos" class="grid_4">
      <a class="menuItem" href="/conocenos.html"><div class="menu5">Conócenos</div></a>
    </div>
    <!-- Termina Barra de herramientas -->
      <div class="clear">&nbsp;</div>
    <!-- escaparate -->
    
    <h1>Lista De Documentos</h1>

    <table>
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Liga</th>
          <th>Fecha</th>
          <% if session[:mod0] == true %>
          <th colspan="3"></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <td><%= document.name %></td>
            <td><%= link_to 'Descargar', document.link %></td>
            <td><%= document.created_at %></td>
            <% if session[:mod0] == true %>
            <td><%= link_to 'Ver', document %></td>
            <td><%= link_to 'Editar', edit_document_path(document) %></td>
            <td><%= link_to 'Borrar', document, method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <% if session[:mod0] == true %>
    <%= link_to 'New Document', new_document_path %>
    <% end %>
    <h1>Nuevo documento</h1>
    <%= render 'form' %>
    </br>
    <!-- fin escaparate-->
    <div class="clear">&nbsp;</div>
    
        
        <!-- Noticias -->
    <div id="flecha" class="grid_1">
      <a href=""><img src="../img/arrow_left.png"></a>
    </div>  
    <div id="noticia_1" class="grid_6">
      <div id="noticia1_titulo" class="noticia_titulo">Valoración Completa</div>
      <div id="noticia1_texto" class="noticia_texto">El Centro de diabetes monterrey le ofrece en un lapso de 6 a 8 horas, llevar a cabo los estudios que se requieran para conocer el estado de los órganos que son afectados por la diabetes.<a href="/valoracion.html" class="ver_mas">Ver mas...</a></div>
    </div>
    <div id="noticia_2" class="grid_6">
      <div id="noticia2_titulo" class="noticia_titulo">Cursos</div>
      <div id="noticia2_texto" class="noticia_texto">Para revisar el material del curso de postgrado en Diabetes por favor dar click en el siguiente enlace. <a href="/cursos.html" class="ver_mas">Ver mas...</a></div>
    </div>
    <div id="noticia_3" class="grid_6">
      <div id="noticia3_titulo" class="noticia_titulo">Laboratorio</div>
      <div id="noticia3_texto" class="noticia_texto">Se realizan exámenes completos de orina y sangre; niveles de azúcar, lipidos, función del riñon e hígado <a href="/servicios.html" class="ver_mas">Ver mas...</a></div>
    </div>
    <div id="flecha" class="grid_1">
      <a href=""><img src="../img/arrow_right.png"></a>
    </div>
      <div class="clear">&nbsp;</div>
    
        
        <!-- Secciones -->
    <div class="secciones">
      <div id="seccion_1" class="grid_5  seccion">
        <div id="seccion_titulo" class="seccion_titulo">Accesorios</div>
        <div id="seccion_texto" class="seccion_texto">En CEDIMO podrá encontrar toda la gama de productos para el control de todos los síntomas de la diabetes, los modelos de medidores de glucosa más usados, glucómetros, lancetas, tiras reactivas, dulces, chocolates, postres sin azúcar.<a href="/accesorios.html" class="ver_mas">Ver mas...</a> 
        </div>
      </div>
      <div id="seccion_2" class="grid_5 seccion">
        <div id="seccion_titulo" class="seccion_titulo">Servicios</div>
        <div id="seccion_texto" class="seccion_texto">Lo más importantes es una valoración integral para el paciente con diabetes. Contamos con diferentes Planes de Atención Médica:Consulta Médico Endocrinólogo – Nutricional, Exámenes... <a href="/servicios.html" class="ver_mas">Ver mas...</a>
        </div>
      </div>
      <div id="seccion_3" class="grid_5 seccion">
        <div id="seccion_titulo" class="seccion_titulo">Nutrición</div>
          <div id="seccion_texto" class="seccion_texto">Una buena nutrición es la base del cuidado de la diabetes, en CEDIMO tenemos experiencia atendiendo al paciente diabético y sabemos que la atención no puede estar separada de una buena nutrición. <a href="/nutricion.html" class="ver_mas">Ver mas...</a>
          </div>
      </div>
      <div id="seccion_4" class="grid_5 seccion">
        <div id="seccion_titulo" class="seccion_titulo">Contacto</div>
        <div id="seccion_texto" class="seccion_texto">
            <a href="mailto:diabetes@cedimo.com.mx" class="cuenta_correo">diabetes@cedimo.com.mx</a>
            <a href="mailto:nutricion@cedimo.com.mx" class="cuenta_correo">nutricion@cedimo.com.mx</a>
            <div class="tel_contacto">Tel. (81) 8347 5534</div>
          </div>
      </div>
    </div>
    <div class="clear">&nbsp;</div>
    <!-- Footer -->
    <div id="pie" class="grid_16 push_2">
        <div id="firma" class="firma"><b>CENTRO DE DIABETES MONTERREY S.A. C.V. </b>    |    Loma Grande No. 2717 Edificio San Francisco M-20  Col. Lomas de San Francisco   |  Monterrey, NL, CP 64710  |  Tel: (81) 8347 5594</div>
    </div>

  </div>
</body>
</html>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Link:</strong>
  <%= @document.link %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @document.owner %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>