config/routes.rb
Rails.application.routes.draw do

  resources :documents

  get 'welcome/index'

  get 'password_resets/new'

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :welcome do
    get 'welcome/index' => :new
    post 'welcome/index' => :create
    delete 'welcome/index' => :destroy
    delete 'welcome/logout' => :destroy
  end
  
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :welcome

  resources :users

  resources :rols

  resources :password_resets

  controller :users do
    get 'recover_password' => :recover_password
    post 'recover_password' => :recover_password 
    get 'new_recover_password' => :new_recover_password
    post 'new_recover_password' => :new_recover_password 
    get 'cambiar_password' => :cambiar_password
    post 'cambiar_password' => :cambiar_password
    get 'new_cambiar_password' => :new_cambiar_password
    post 'new_cambiar_password' => :new_cambiar_password
  end 

  

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cedimo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!--<div id="columns">
		<div id="side">
			<%# if session[:user_id] %>
				<li><%#= link_to 'Users',users_path%></li>
				<%#= "#{session[:rol_id]}"%>
				<%#= "#{session[:uname]}"%>
				<p>Bienvenido <%#= "#{session[:thename]}"%>||</p>
				<%#= button_to 'Logout', logout_path, method: :delete %>
			    <%#= link_to "Cambiar Password", new_cambiar_password_path %>
			<%# else %>
				<p>Bienvenido Visitante||</p>
				<%#= button_to 'Iniciar Sesion', login_path, method: :new %>
			<%# end %>
		</div>
	</div>-->
	<div id="main">
		<%= yield %>
	</div>


</body>
</html>